apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  image:
    application: bargovic/cp-kafka-rest:7.3.1-ubi8-aarch64
    init: bargovic/confluent-init-container:2.5.1.aarch64
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
  configOverrides:
    server:
      # enable mtls to mtls principal propagation
      #- "confluent.rest.auth.propagate.method=SSL"
      #- "kafka.rest.resource.extension.class=io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension"
  listeners:
    external:
      externalAccess:
        type: loadBalancer
        loadBalancer:
          domain: fios-router.home
  podTemplate:
    resources:
      limits:
      memory: 512Mi
      cpu: 1
    podSecurityContext:
     runAsUser: 0