
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent-ironbank
spec:
  replicas: 2
  image:
    application: bargovic/cp-ksqldb-server-repo1:6.2.1
    init: confluentinc/confluent-init-container:2.0.3
    pullSecretRef:
      - ironbank-registry
  dataVolumeCapacity: 10Gi
  tls:
    secretRef: tls-ksqldb
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-ironbank.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent-ironbank.svc.cluster.local:8081
      tls:
        enabled: true
  podTemplate:
    podSecurityContext: { } # Disable the custom pod security context, to use the default
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent-ironbank
spec:
  replicas: 1
  image:
    application: bargovic/cp-schema-registry-repo1:6.2.1.0
    init: confluentinc/confluent-init-container:2.0.3
    pullSecretRef:
      - ironbank-registry
  tls:
    secretRef: tls-schemaregistry
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-ironbank.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
  podTemplate:
    podSecurityContext: { } # Disable the custom pod security context, to use the default
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent-ironbank
spec:
  replicas: 1
  image:
    application: bargovic/cp-enterprise-control-center-repo1:6.2.1.0
    init: confluentinc/confluent-init-container:2.0.3
    pullSecretRef:
      - ironbank-registry
  dataVolumeCapacity: 10Gi
  authentication:
    type: basic
    basic:
      roles:
        - Administrators
        - Restricted
      restrictedRoles:
        - Restricted
      secretRef: basicsecret
  tls:
    secretRef: tls-controlcenter
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-ironbank.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent-ironbank.svc.cluster.local:8081
      tls:
        enabled: true
    ksqldb:
    - name: ksql
      url: https://ksqldb.confluent-ironbank.svc.cluster.local:8088
      tls:
        enabled: true
    connect:
    - name: connect-dev
      url:  https://connect.confluent-ironbank.svc.cluster.local:8083
      tls:
        enabled: true
  podTemplate:
    podSecurityContext: { } # Disable the custom pod security context, to use the default
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent-ironbank
spec:
  replicas: 2
  image:
    application:  bargovic/cp-server-connect:6.2.1-1
    init: confluentinc/confluent-init-container:2.0.3
    pullSecretRef:
      - ironbank-registry
  tls:
    secretRef: tls-connect
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent-ironbank.svc.cluster.local:9071
      authentication:
        type: mtls
      tls:
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent-ironbank.svc.cluster.local:8081
      tls:
        enabled: true
  podTemplate:
    podSecurityContext: { } # Disable the custom pod security context, to use the default