
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  image:
    application: bargovic/cp-ksqldb-server:7.3.1-ubi8-aarch64
    init: bargovic/confluent-init-container:2.5.1.aarch64
  dataVolumeCapacity: 10Gi
  configOverrides:
    jvm:
      - "-Xms512M"
      - "-Xmx512M"
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: fios-router.home
  podTemplate:
    resources:
      limits:
        memory: 1Gi
        cpu: 1
    podSecurityContext:
      runAsUser: 0
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    application: bargovic/cp-schema-registry:7.3.1-ubi8-aarch64
    init: bargovic/confluent-init-container:2.5.1.aarch64
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
  podTemplate:
    resources:
      limits:
        memory: 512Mi
        cpu: 1
    podSecurityContext:
      runAsUser: 0
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: bargovic/cp-enterprise-control-center:7.3.1-ubi8-aarch64
    init: bargovic/confluent-init-container:2.5.1.aarch64
  dataVolumeCapacity: 15Gi
  storageClass:
    name: local-path
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksql
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect-dev
      url:  http://connect.confluent.svc.cluster.local:8083
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: fios-router.home
  podTemplate:
    tolerations:
      - key: "allowOnMaster"
        operator: "Exists"
        effect: "NoSchedule"
    resources:
      limits:
        memory: 2.5Gi
        cpu: 2
    podSecurityContext:
      runAsUser: 0
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application:  bargovic/cp-server-connect:7.3.1-ubi8-aarch64
    init: bargovic/confluent-init-container:2.5.1.aarch64
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: fios-router.home
  podTemplate:
    resources:
      limits:
        memory: 1.5Gi
        cpu: 1
    podSecurityContext:
      runAsUser: 0