apiVersion: v1
kind: Service
metadata:
  name: syslog-lb
spec:
  type: LoadBalancer
  ports:
    - port: 5454
      targetPort: 5454
      protocol: UDP
      name: connect-udp
  selector:
    app: connect