apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic-test-a
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
  configs:
    cleanup.policy: "delete"
    retention.ms: "259200000"
    segment.ms: "259200000"
  kafkaRest:
    endpoint: https://kafka.confluent.svc.cluster.local:8090
    authentication:
      type: bearer
      bearer:
        secretRef: mds-client